site_name: PhysioEx 
site_url: https://guidogagl.github.io/physioex/
nav:
    - Home: index.md
    - Train: train.md
    - Explain: unavailable.md
    - Data: unavailable.md
    - Examples: unavailable.md
    - Contribute: unavailable.md
theme:
  name: material
  favicon: img/logo.png 
  icon:
    logo: fontawesome/solid/kiwi-bird
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: slate
    primary: pink
    accent: pink

repo_name: guidogagl/physioex
repo_url: https://github.com/guidogagl/physioex

plugins:
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/guidogagl
    - icon: fontawesome/solid/globe
      link: https://guidogagl.github.io/
    - icon: fontawesome/brands/google-scholar
    #  link: https://scholar.google.com/citations?hl=en&user=8EczeSIAAAAJ&view_op=list_works&authuser=1&gmla=AH70aAXBbb_-rGzDj_dBksWED8IN9ZEu82KU8sbVIEl7KzRmvje06i4p0K4QxpdLOhJnQFneN4VMBPIkc99NwVe0

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.superfences 
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/guidogagl"  target="_blank" rel="noopener">Guido Gagliardi</a>