wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717675552
    t:
      1:
      - 1
      - 5
      - 9
      - 32
      - 53
      - 55
      - 103
      3:
      - 13
      - 23
      4: 3.10.0
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
