wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717673729
    t:
      1:
      - 1
      - 5
      - 9
      - 32
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 32
      - 53
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.10.0
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
model:
  desc: null
  value: chambon2018
dataset:
  desc: null
  value: dreem
version:
  desc: null
  value: dodh
monitor:
  desc: null
  value: val_acc
fold:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 16
loss:
  desc: null
  value: cel
